file:
    pattern:  /
    defaults: { _controller: "MavTestUploadBundle:File:index" }

file_show:
    pattern:  /{id}/show
    defaults: { _controller: "MavTestUploadBundle:File:show" }

file_new:
    pattern:  /new
    defaults: { _controller: "MavTestUploadBundle:File:new" }

file_create:
    pattern:  /create
    defaults: { _controller: "MavTestUploadBundle:File:create" }
    requirements: { _method: post }

file_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "MavTestUploadBundle:File:edit" }

file_update:
    pattern:  /{id}/update
    defaults: { _controller: "MavTestUploadBundle:File:update" }
    requirements: { _method: post|put }

file_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "MavTestUploadBundle:File:delete" }
    requirements: { _method: post|delete }
