parameters:
#    mav_test_upload.example.class: Mav\TestUploadBundle\Example

services:
#    mav_test_upload.example:
#        class: %mav_test_upload.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
